name: "Deploy: Build & Publish Site to GitHub Pages"

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code from 'main'
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: pip install pyyaml jsonschema

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Build Typst documents
        run: python scripts/build_docs.py --outdir dist/docs

      - name: Generate static site
        run: python scripts/generate_site.py --site-dir site --outdir dist --docs-folder docs

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

