name: "PR Checks: Validate & Preview"

on:
  pull_request:
    branches: [main]

jobs:
  validate-pr-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code (HEAD)
        uses: actions/checkout@v4

      - name: Fetch main branch (for comparison)
        run: git fetch origin main --depth=1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml jsonschema

      - name: Run PR Semantic Check
        run: python scripts/validate_pr_changes.py

  build-and-validate:
    runs-on: ubuntu-latest
    needs: [validate-pr-changes]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml jsonschema

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Execute Python build script (full validation & compile)
        run: python scripts/build_docs.py --outdir=dist/docs

      - name: Upload PDF artifacts for the reviewer
        uses: actions/upload-artifact@v4
        with:
          name: pdf-previews
          path: ./dir/docs-output/
