name: "PR Lifecycle: Validate, Build & Deploy"

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main]

jobs:
  validate-pr-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code (HEAD)
        uses: actions/checkout@v4

      - name: Fetch main branch (for comparison)
        run: git fetch origin main --depth=1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run PR Semantic Check
        run: python scripts/validate_pr_changes.py

  build-and-validate:
    runs-on: ubuntu-latest
    needs: [validate-pr-changes]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Build Typst documents into '_site/documents'
        run: python scripts/build-docs.py --outdir _site/documents

      - name: Generate static site into '_site'
        run: python scripts/generate-site.py --outdir _site --site-dir site

      - name: Upload PDF artifact for reviewer
        uses: actions/upload-artifact@v4
        with:
          name: pdf-previews
          path: ./_site/documents/

      - name: Upload full site artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: built-site
          path: ./_site/

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-validate]
    if: github.event.pull_request.merged == true

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download full site artifact
        uses: actions/download-artifact@v4
        with:
          name: built-site
          path: ./_site

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
