name: "PR Checks: Validate & Preview"

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install pyyaml jsonschema

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          # We need fetch-depth: 0 to get all history for git diff
          fetch-depth: 0

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: 'base_checkout'

      - name: Generate base model
        run: |
          python base_checkout/scripts/validate_pr_changes.py generate \
            --output base-model.json

      - name: Generate PR model
        run: |
          python scripts/validate_pr_changes.py generate \
            --output pr-model.json

      - name: Get changed files
        run: |
          BASE_COMMIT=$(git merge-base ${{ github.base_ref }} HEAD)
          git diff --name-only ${BASE_COMMIT} HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt
        shell: bash
      
      - name: Validate document changes
        run: |
          python scripts/validate_pr_changes.py compare \
            base-model.json \
            pr-model.json \
            changed_files.txt

      - name: Build docs from PR
        run: python scripts/build_docs.py --outdir dist/docs
      
      - name: Upload Build Artifacts (PDFs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-docs-preview
          path: dist/docs/
          retention-days: 7

      - name: Upload Validation Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-artifacts
          path: |
            pr-model.json
            base-model.json
            changed_files.txt
          retention-days: 7